-- Generated from content/vocabulary.json by node scripts/generate-vocabulary.mjs.
-- Check without rewriting: node scripts/generate-vocabulary.mjs --check
-- Adds vocabulary only; existing lessons, answers, and learning history are preserved.
INSERT OR IGNORE INTO pl_content_versions (version, track_id, status, notes, created_at) VALUES ('vocabulary-2026.1', 'track-a1', 'published', '生活で使う単語80語。8場面・各10語、独自例文つき。既存カリキュラムとは独立して学習する。', strftime('%Y-%m-%dT%H:%M:%fZ','now'));

-- supermarket: スーパー・買い物
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-chleb', 'word', 'chleb', 'パン', 'bread', '男性名詞。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["chleb"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-chleb', 'Proszę chleb.', 'パンをください。', NULL, 1);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-woda', 'word', 'woda', '水', 'water', '女性名詞。注文では wodę。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["woda"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-woda', 'Proszę wodę.', '水をください。', NULL, 2);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-mleko', 'word', 'mleko', '牛乳', 'milk', '中性名詞。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["mleko"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-mleko', 'To jest mleko.', 'これは牛乳です。', NULL, 3);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-kawa', 'word', 'kawa', 'コーヒー', 'coffee', '女性名詞。注文では kawę。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["kawa"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-kawa', 'Proszę kawę.', 'コーヒーをください。', NULL, 4);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-sklep', 'word', 'sklep', '店', 'shop', '男性名詞。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["sklep"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-sklep', 'Gdzie jest sklep?', '店はどこですか？', NULL, 5);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-ser', 'word', 'ser', 'チーズ', 'cheese', '男性名詞。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["ser"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-ser', 'Kupuję ser.', 'チーズを買います。', NULL, 6);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-jajko', 'word', 'jajko', '卵', 'egg', '中性名詞。複数は jajka。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["jajko"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-jajko', 'To jest jajko.', 'これは卵です。', NULL, 7);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-maslo', 'word', 'masło', 'バター', 'butter', '中性名詞。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["masło"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-maslo', 'Proszę masło.', 'バターをください。', NULL, 8);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-jablko', 'word', 'jabłko', 'りんご', 'apple', '中性名詞。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["jabłko"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-jablko', 'Jem jabłko.', 'りんごを食べます。', NULL, 9);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-supermarket-cena', 'word', 'cena', '値段', 'price', '女性名詞。', 'supermarket', '["vocabulary","scene:supermarket","part:noun"]', '["cena"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'supermarket', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-supermarket-cena', 'Jaka jest cena?', '値段はいくらですか？', NULL, 10);

-- cafe: カフェ・食事
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-herbata', 'word', 'herbata', 'お茶', 'tea', '女性名詞。注文では herbatę。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["herbata"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-herbata', 'Proszę herbatę.', 'お茶をください。', NULL, 11);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-cukier', 'word', 'cukier', '砂糖', 'sugar', '男性名詞。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["cukier"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-cukier', 'Poproszę cukier.', '砂糖をお願いします。', NULL, 12);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-filizanka', 'word', 'filiżanka', 'カップ', 'cup', '女性名詞。コーヒーやお茶用の取っ手付きカップ。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["filiżanka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-filizanka', 'To jest moja filiżanka.', 'これは私のカップです。', NULL, 13);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-szklanka', 'word', 'szklanka', 'グラス', 'drinking glass', '女性名詞。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["szklanka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-szklanka', 'Szklanka jest pusta.', 'グラスは空です。', NULL, 14);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-ciasto', 'word', 'ciasto', 'ケーキ', 'cake', '中性名詞。生地の意味もあります。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["ciasto"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-ciasto', 'To ciasto jest dobre.', 'このケーキはおいしいです。', NULL, 15);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-kanapka', 'word', 'kanapka', 'サンドイッチ', 'sandwich', '女性名詞。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["kanapka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-kanapka', 'Jem kanapkę.', 'サンドイッチを食べます。', NULL, 16);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-rachunek', 'word', 'rachunek', '勘定・請求書', 'bill', '男性名詞。飲食店の会計でも使います。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["rachunek"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-rachunek', 'Poproszę rachunek.', 'お会計をお願いします。', NULL, 17);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-stolik', 'word', 'stolik', 'テーブル', 'table', '男性名詞。カフェなどの小さなテーブル。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["stolik"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-stolik', 'Ten stolik jest wolny.', 'このテーブルは空いています。', NULL, 18);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-lyzeczka', 'word', 'łyżeczka', 'ティースプーン', 'teaspoon', '女性名詞。łyżka（スプーン）の小さいもの。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["łyżeczka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-lyzeczka', 'Poproszę łyżeczkę.', 'ティースプーンをお願いします。', NULL, 19);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-cafe-sok', 'word', 'sok', 'ジュース', 'juice', '男性名詞。', 'cafe', '["vocabulary","scene:cafe","part:noun"]', '["sok"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'cafe', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-cafe-sok', 'Proszę sok.', 'ジュースをください。', NULL, 20);

-- transport: 交通・移動
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-bilet', 'word', 'bilet', '切符', 'ticket', '男性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["bilet"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-bilet', 'Proszę jeden bilet.', '切符を1枚ください。', NULL, 21);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-autobus', 'word', 'autobus', 'バス', 'bus', '男性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["autobus"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-autobus', 'Ten autobus jedzie do centrum.', 'このバスは中心部へ行きます。', NULL, 22);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-tramwaj', 'word', 'tramwaj', '路面電車', 'tram', '男性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["tramwaj"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-tramwaj', 'Tramwaj już jedzie.', '路面電車がもう来ています。', NULL, 23);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-pociag', 'word', 'pociąg', '列車', 'train', '男性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["pociąg"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-pociag', 'Pociąg jest na peronie.', '列車はホームにあります。', NULL, 24);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-przystanek', 'word', 'przystanek', '停留所', 'stop', '男性名詞。バスや路面電車の停留所。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["przystanek"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-przystanek', 'Gdzie jest przystanek?', '停留所はどこですか？', NULL, 25);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-dworzec', 'word', 'dworzec', '駅・ターミナル', 'station', '男性名詞。主に鉄道駅やバスターミナル。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["dworzec"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-dworzec', 'Gdzie jest dworzec?', '駅はどこですか？', NULL, 26);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-peron', 'word', 'peron', 'ホーム', 'platform', '男性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["peron"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-peron', 'To jest peron drugi.', 'これは2番ホームです。', NULL, 27);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-lotnisko', 'word', 'lotnisko', '空港', 'airport', '中性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["lotnisko"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-lotnisko', 'Jadę na lotnisko.', '空港へ行きます。', NULL, 28);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-taksowka', 'word', 'taksówka', 'タクシー', 'taxi', '女性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["taksówka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-taksowka', 'Taksówka już czeka.', 'タクシーがもう待っています。', NULL, 29);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-transport-opoznienie', 'word', 'opóźnienie', '遅れ', 'delay', '中性名詞。', 'transport', '["vocabulary","scene:transport","part:noun"]', '["opóźnienie"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'transport', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-transport-opoznienie', 'Pociąg ma opóźnienie.', '列車が遅れています。', NULL, 30);

-- home: 家・住まい
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-dom', 'word', 'dom', '家', 'house', '男性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["dom"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-dom', 'To jest mój dom.', 'これは私の家です。', NULL, 31);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-mieszkanie', 'word', 'mieszkanie', '住居・アパート', 'flat', '中性名詞。建物内の住居を指します。', 'home', '["vocabulary","scene:home","part:noun"]', '["mieszkanie"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-mieszkanie', 'To mieszkanie jest małe.', 'このアパートは小さいです。', NULL, 32);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-pokoj', 'word', 'pokój', '部屋', 'room', '男性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["pokój"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-pokoj', 'To jest mój pokój.', 'これは私の部屋です。', NULL, 33);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-kuchnia', 'word', 'kuchnia', 'キッチン', 'kitchen', '女性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["kuchnia"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-kuchnia', 'Kuchnia jest mała.', 'キッチンは小さいです。', NULL, 34);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-lazienka', 'word', 'łazienka', '浴室・洗面所', 'bathroom', '女性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["łazienka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-lazienka', 'Gdzie jest łazienka?', '浴室はどこですか？', NULL, 35);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-klucz', 'word', 'klucz', '鍵', 'key', '男性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["klucz"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-klucz', 'Mam klucz.', '鍵を持っています。', NULL, 36);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-drzwi', 'word', 'drzwi', 'ドア', 'door', '複数形だけで使う名詞。ドア1つでも drzwi。', 'home', '["vocabulary","scene:home","part:noun"]', '["drzwi"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-drzwi', 'Drzwi są otwarte.', 'ドアが開いています。', NULL, 37);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-okno', 'word', 'okno', '窓', 'window', '中性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["okno"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-okno', 'Okno jest zamknięte.', '窓は閉まっています。', NULL, 38);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-lozko', 'word', 'łóżko', 'ベッド', 'bed', '中性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["łóżko"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-lozko', 'Łóżko jest wygodne.', 'ベッドは快適です。', NULL, 39);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-home-pralka', 'word', 'pralka', '洗濯機', 'washing machine', '女性名詞。', 'home', '["vocabulary","scene:home","part:noun"]', '["pralka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'home', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-home-pralka', 'Pralka nie działa.', '洗濯機が動きません。', NULL, 40);

-- health: 健康・薬局
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-lekarz', 'word', 'lekarz', '医師', 'doctor', '男性名詞。女性の医師は lekarka。', 'health', '["vocabulary","scene:health","part:noun"]', '["lekarz"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-lekarz', 'Potrzebuję lekarza.', '医師が必要です。', NULL, 41);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-apteka', 'word', 'apteka', '薬局', 'pharmacy', '女性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["apteka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-apteka', 'Gdzie jest apteka?', '薬局はどこですか？', NULL, 42);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-lek', 'word', 'lek', '薬', 'medicine', '男性名詞。複数は leki。', 'health', '["vocabulary","scene:health","part:noun"]', '["lek"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-lek', 'Ten lek jest na kaszel.', 'この薬はせき用です。', NULL, 43);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-recepta', 'word', 'recepta', '処方箋', 'prescription', '女性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["recepta"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-recepta', 'Mam receptę.', '処方箋を持っています。', NULL, 44);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-bol', 'word', 'ból', '痛み', 'pain', '男性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["ból"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-bol', 'Czuję ból.', '痛みを感じます。', NULL, 45);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-goraczka', 'word', 'gorączka', '発熱', 'fever', '女性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["gorączka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-goraczka', 'Mam gorączkę.', '熱があります。', NULL, 46);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-glowa', 'word', 'głowa', '頭', 'head', '女性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["głowa"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-glowa', 'Boli mnie głowa.', '頭が痛いです。', NULL, 47);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-brzuch', 'word', 'brzuch', 'お腹', 'belly', '男性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["brzuch"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-brzuch', 'Boli mnie brzuch.', 'お腹が痛いです。', NULL, 48);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-kaszel', 'word', 'kaszel', 'せき', 'cough', '男性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["kaszel"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-kaszel', 'Mam kaszel.', 'せきが出ます。', NULL, 49);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-health-pomoc', 'word', 'pomoc', '助け', 'help', '女性名詞。', 'health', '["vocabulary","scene:health","part:noun"]', '["pomoc"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'health', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-health-pomoc', 'Potrzebuję pomocy.', '助けが必要です。', NULL, 50);

-- errands: 手続き・用事
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-poczta', 'word', 'poczta', '郵便局', 'post office', '女性名詞。郵便の意味もあります。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["poczta"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-poczta', 'Gdzie jest poczta?', '郵便局はどこですか？', NULL, 51);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-paczka', 'word', 'paczka', '小包', 'parcel', '女性名詞。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["paczka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-paczka', 'To jest moja paczka.', 'これは私の小包です。', NULL, 52);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-list', 'word', 'list', '手紙', 'letter', '男性名詞。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["list"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-list', 'Wysyłam list.', '手紙を送ります。', NULL, 53);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-bank', 'word', 'bank', '銀行', 'bank', '男性名詞。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["bank"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-bank', 'Bank jest blisko.', '銀行は近くにあります。', NULL, 54);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-karta', 'word', 'karta', 'カード', 'card', '女性名詞。支払いでは kartą（カードで）。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["karta"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-karta', 'Płacę kartą.', 'カードで払います。', NULL, 55);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-gotowka', 'word', 'gotówka', '現金', 'cash', '女性名詞。支払いでは gotówką（現金で）。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["gotówka"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-gotowka', 'Płacę gotówką.', '現金で払います。', NULL, 56);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-urzad', 'word', 'urząd', '役所', 'government office', '男性名詞。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["urząd"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-urzad', 'Urząd jest otwarty.', '役所は開いています。', NULL, 57);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-dokument', 'word', 'dokument', '書類', 'document', '男性名詞。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["dokument"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-dokument', 'Mam ten dokument.', 'その書類を持っています。', NULL, 58);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-formularz', 'word', 'formularz', '記入用紙', 'form', '男性名詞。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["formularz"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-formularz', 'Wypełniam formularz.', '用紙に記入しています。', NULL, 59);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-errands-podpis', 'word', 'podpis', '署名', 'signature', '男性名詞。', 'errands', '["vocabulary","scene:errands","part:noun"]', '["podpis"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'errands', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-errands-podpis', 'Tutaj jest mój podpis.', 'ここに私の署名があります。', NULL, 60);

-- people: 人・関係
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-czlowiek', 'word', 'człowiek', '人', 'person', '男性名詞。複数は ludzie。', 'people', '["vocabulary","scene:people","part:noun"]', '["człowiek"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-czlowiek', 'To dobry człowiek.', 'その人はいい人です。', NULL, 61);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-kobieta', 'word', 'kobieta', '女性', 'woman', '女性名詞。', 'people', '["vocabulary","scene:people","part:noun"]', '["kobieta"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-kobieta', 'Ta kobieta pracuje tutaj.', 'その女性はここで働いています。', NULL, 62);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-mezczyzna', 'word', 'mężczyzna', '男性', 'man', 'aで終わりますが男性名詞。', 'people', '["vocabulary","scene:people","part:noun"]', '["mężczyzna"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-mezczyzna', 'Ten mężczyzna jest moim sąsiadem.', 'その男性は私の隣人です。', NULL, 63);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-dziecko', 'word', 'dziecko', '子ども', 'child', '中性名詞。複数は dzieci。', 'people', '["vocabulary","scene:people","part:noun"]', '["dziecko"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-dziecko', 'Dziecko śpi.', '子どもが寝ています。', NULL, 64);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-rodzina', 'word', 'rodzina', '家族', 'family', '女性名詞。', 'people', '["vocabulary","scene:people","part:noun"]', '["rodzina"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-rodzina', 'Moja rodzina jest w Japonii.', '私の家族は日本にいます。', NULL, 65);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-przyjaciel', 'word', 'przyjaciel', '友人', 'friend', '男性名詞。女性の友人は przyjaciółka。', 'people', '["vocabulary","scene:people","part:noun"]', '["przyjaciel"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-przyjaciel', 'To jest mój przyjaciel.', 'これは私の友人です。', NULL, 66);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-sasiad', 'word', 'sąsiad', '隣人', 'neighbour', '男性名詞。女性の隣人は sąsiadka。', 'people', '["vocabulary","scene:people","part:noun"]', '["sąsiad"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-sasiad', 'Mój sąsiad jest miły.', '私の隣人は親切です。', NULL, 67);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-sprzedawca', 'word', 'sprzedawca', '販売員', 'salesperson', 'aで終わりますが男性名詞。女性は sprzedawczyni。', 'people', '["vocabulary","scene:people","part:noun"]', '["sprzedawca"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-sprzedawca', 'Sprzedawca mi pomaga.', '販売員が私を手伝ってくれています。', NULL, 68);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-pracownik', 'word', 'pracownik', '職員・従業員', 'employee', '男性名詞。女性は pracownica。', 'people', '["vocabulary","scene:people","part:noun"]', '["pracownik"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-pracownik', 'Pracownik jest w biurze.', '職員は事務所にいます。', NULL, 69);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-people-imie', 'word', 'imię', '名前', 'first name', '中性名詞。個人の名を指します。', 'people', '["vocabulary","scene:people","part:noun"]', '["imię"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'people', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-people-imie', 'Jak masz na imię?', '名前は何ですか？', NULL, 70);

-- time: 時間・予定
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-dzis', 'word', 'dziś', '今日', 'today', '副詞。dzisiaj と同じ意味。', 'time', '["vocabulary","scene:time","part:adverb"]', '["dziś","dzisiaj"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-dzis', 'Dziś pracuję.', '今日は働きます。', NULL, 71);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-jutro', 'word', 'jutro', '明日', 'tomorrow', '副詞。', 'time', '["vocabulary","scene:time","part:adverb"]', '["jutro"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-jutro', 'Jutro mam wolne.', '明日は休みです。', NULL, 72);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-wczoraj', 'word', 'wczoraj', '昨日', 'yesterday', '副詞。', 'time', '["vocabulary","scene:time","part:adverb"]', '["wczoraj"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-wczoraj', 'Wczoraj padało.', '昨日は雨が降りました。', NULL, 73);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-teraz', 'word', 'teraz', '今', 'now', '副詞。', 'time', '["vocabulary","scene:time","part:adverb"]', '["teraz"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-teraz', 'Teraz jestem w domu.', '今は家にいます。', NULL, 74);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-pozniej', 'word', 'później', 'あとで', 'later', '副詞。', 'time', '["vocabulary","scene:time","part:adverb"]', '["później"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-pozniej', 'Zadzwonię później.', 'あとで電話します。', NULL, 75);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-rano', 'word', 'rano', '朝に', 'in the morning', '時を表す副詞。', 'time', '["vocabulary","scene:time","part:adverb"]', '["rano"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-rano', 'Rano piję kawę.', '朝にコーヒーを飲みます。', NULL, 76);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-wieczor', 'word', 'wieczór', '夕方・夜', 'evening', '男性名詞。「夜に」は wieczorem。', 'time', '["vocabulary","scene:time","part:noun"]', '["wieczór"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-wieczor', 'Wieczór jest spokojny.', '穏やかな夜です。', NULL, 77);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-dzien', 'word', 'dzień', '日・1日', 'day', '男性名詞。', 'time', '["vocabulary","scene:time","part:noun"]', '["dzień"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-dzien', 'To był dobry dzień.', 'いい1日でした。', NULL, 78);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-tydzien', 'word', 'tydzień', '週', 'week', '男性名詞。', 'time', '["vocabulary","scene:time","part:noun"]', '["tydzień"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-tydzien', 'Za tydzień wracam.', '1週間後に戻ります。', NULL, 79);
INSERT OR IGNORE INTO pl_learning_items (id, type, polish, meaning_ja, meaning_en, grammar_note, topic, tags_json, accepted_answers_json, content_version, status, created_at, cefr_level, skills_json, scene, register, speaker_gender, dialogue_role, source_kind) VALUES ('voc-time-godzina', 'word', 'godzina', '時間・1時間', 'hour', '女性名詞。時刻を尋ねるときにも使います。', 'time', '["vocabulary","scene:time","part:noun"]', '["godzina"]', 'vocabulary-2026.1', 'published', strftime('%Y-%m-%dT%H:%M:%fZ','now'), 'A1', '["listening","spoken_production"]', 'time', 'neutral', 'any', 'learner', 'independent');
INSERT OR IGNORE INTO pl_vocabulary_details (item_id, example_pl, example_ja, owner_profile_id, sort_order) VALUES ('voc-time-godzina', 'Która jest godzina?', '今何時ですか？', NULL, 80);
